#!/bin/bash

source scripts/ips

for i in "${!IPS[@]}"; do
    IP=${IPS[$i]}
    echo install "$IP";
    ssh almalinux@"$IP" "sudo dnf module install nodejs:14 -y; mkdir ~/.npm-global;npm config set prefix '~/.npm-global'; echo 'export PATH=~/.npm-global/bin:$PATH' > ~/.bashrc; source ~/.bashrc; npm i -g pm2";
done
