#!/bin/bash
#
#ssh debian@51.210.159.247 "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;"
#ssh debian@51.68.91.161 "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;"
#ssh debian@51.91.149.177 "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;"
#ssh debian@51.91.150.15 "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;"
#ssh debian@51.91.151.117 "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;"

source scripts/ips

for ip in "${IPS[@]}"; do
    echo reload to "$ip";
#    ssh debian@"$ip" "cd server; pm2 flush; pm2 delete mc.config.js; pm2 start mc.config.js;";
done
